### ISSUE TITLE
 Cannot read properties of undefined (reading 'schemas')

### ISSUE THREAD

**Issue by melonlly** [ldc2726/swagger-ts#3]
D:\software\nvm\nvm\v16.16.0\node_modules\swagger-ts-api\utils\formatV3.js:41
    for (const i in res.data['components']['schemas']) {
TypeError: Cannot read properties of undefined (reading 'schemas')
    at exports.formatV3 (D:\software\nvm\nvm\v16.16.0\node_modules\swagger-ts-api\utils\formatV3.js:41:43)
    at getSwaggerJson (D:\software\nvm\nvm\v16.16.0\node_modules\swagger-ts-api\bin\main.js:261:11)

**Comment by ldc2726** [comment]
version？swagger.json?
